// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"dataflow/pkg/api/handler/user"
	user4 "dataflow/pkg/api/usecase/user"
	"dataflow/pkg/domain/repository"
	user3 "dataflow/pkg/domain/service/user"
	user2 "dataflow/pkg/infrastructure/mysql/user"
)

// Injectors from wire.go:

func InitUserAPI(masterTxManager repository.MasterTxManager) user.Server {
	userRepository := user2.New(masterTxManager)
	service := user3.New(userRepository)
	interactor := user4.New(masterTxManager, service)
	server := user.New(interactor)
	return server
}
